import Head from 'next/head';
import Container from '../components/common/Container';
import BookTheBest from '../components/homepage/BookTheBest';

import ExploreOurDesert from '../components/homepage/ExploreOurDesert';
import WhyChoose from '../components/homepage/WhyChoose';

import Hero from '../components/homepage/Hero';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Desert Raja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Container>
        <BookTheBest />
      </Container>
      <ExploreOurDesert />
      <WhyChoose />
    </div>
  );
}
